name: Scheduled Price Update

on:
  schedule:
    - cron: '0 0 * * 0' # Se ejecuta cada domingo a las 00:00 UTC
  workflow_dispatch:      # Permite ejecutarlo manualmente desde el botón "Actions"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run All Scrapers
        #run: |
        #  cd scrapers
        #  python run_all.py
        run: echo "Skipping price update"

      - name: Upload debug screenshot on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot
          path: error_debug.png

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f data/*.json || echo "There is no folder data yet"
          if git diff --staged --quiet; then
            echo "There is no change on the price. Skipping commit."
          else
            git commit -m "chore: automated price update [skip ci]"
            git push
          fi
